version: '3'
services:
  rust_app:
    image: rust:latest
    working_dir: /app
    volumes:
      - .:/app # mount the project directory
    ports:
      - "8000:8000"  
    depends_on:
      - mysql_db
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - my-network
    command: bash -c "cargo install cargo-watch && cargo watch -x run"
    # command: bash -c "cargo build --release && ./target/release/todos_web_api"

  mysql_db:
    image: mysql:latest
    restart: always  
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql 
    ports:
      - "3306:3306" 
    networks:
      - my-network
networks:
  my-network:  # Define the network
    driver: bridge
volumes:
  mysql_data: