CREATE TABLE IF NOT EXISTS access_tokens (
    id              BIGINT SIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    token           VARCHAR(255) UNIQUE NOT NULL,
    user_id         BIGINT SIGNED NOT NULL,
    expires_at      TIMESTAMP NOT NULL,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY     (user_id) REFERENCES users(id)
);